### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ThasianX**
Create a tag with the version "1.0.0". Draft a release called "Initial release".

### CODE REVIEW

**Comment by eonist** [comment]
Thanks 😻 personally I use `.branch("master")` but if version tag works 🎉

**Comment by eonist** [comment]
I cleaned up the contribution a bit. Some misconceptions. you can use same code for Xcode usage etc. Let me know if you need further clarification.

**Comment by ThasianX** [comment]
Related thread on this issue: https://stackoverflow.com/a/58034307/6074750

I've tried doing exactly what this repository is doing in actual source code, not unit tests. It doesn't work because the asset I want(ie a png) isn't available at runtime even though I can go into the actual derived data and see the png exists. I actually don't know the specifics regarding this but if you do, I would love to hear your thoughts.

**Comment by ThasianX** [comment]
Yea and also, creating tags is 1000% better than tracking a branch. SPM is meant to be used with semantic versioning and it's just easier for someone who's going to be using this package to reference a tag instead of a branch(like it's easier to track what changed - is it backwards compatible or not). But since this is a pretty small repo and pretty unlikely to change and probably going to be invalid when Swift 5.3 becomes available, I guess referencing master is fine.

**Comment by eonist** [comment]
Yepp. Its so tiny. that's why there is no tags. I can make a 1.0.0 tag tho. 
- I think if you put that .png inside a .bundle the data will exist. (only iOS, Mac can derive from normal folders )
- I parse files from SPM in terminal/Github Actions  and unit tests in Xcode. Thats the point of this repo. to write code once and have the assets available in all types of unit tests etc. 

Try the .bundle approach (mean no disrespect if you already know this 😬). If that doesn't work or its not related to this, ill commit example project with the setup I use in a couple of private projects ✌️

**Pull request merged**
